title: "Nuclear Power Plant Safety NLP"
baseURL: "https://albli.github.io/nuclear-power-plant-safety-nlp/"
defaultContentLanguage: en

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5
      disable: false
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-netlify
      disable: false
